package com.example.kimlongflower;

import java.util.HashMap;

public class CreateEmptyDatabase {
    //Method to create new storage of flowers
    public static HashMap<String,String> CreateEmptyDatabase(){
        HashMap<String,String> userInfo = new HashMap<>();
        userInfo.put("Cúc chùm cánh dài","0 bó");
        userInfo.put("AT","0 bó");
        userInfo.put("Cúc chùm trắng","0 bó");
        userInfo.put("Cúc chùm mai cam","0 bó");
        userInfo.put("Cúc chùm mai đỏ","0 bó");
        userInfo.put("Cúc chùm mai tím","0 bó");
        userInfo.put("Cúc chùm mai hồng","0 bó");
        userInfo.put("Cúc chùm mai vàng","0 bó");
        userInfo.put("Cúc chùm lan tím","0 bó");
        userInfo.put("Cúc chùm Calimero (Kaly) đủ màu","0 bó");
        userInfo.put("Cúc chùm farm tím","0 bó");
        userInfo.put("Cúc chùm farm vàng","0 bó");
        userInfo.put("Cúc chùm farm trắng","0 bó");
        userInfo.put("Cúc chùm thạch bích đậm","0 bó");
        userInfo.put("Cúc chùm thạch bích nhạt","0 bó");
        userInfo.put("Cúc chùm nhị nâu","0 bó");
        userInfo.put("Cúc chùm Mona trắng","0 bó");
        userInfo.put("Cúc chùm Mona vàng","0 bó");
        userInfo.put("Cúc chùm tai chuột","0 bó");
        userInfo.put("Cúc chùm nhím xanh","0 bó");
        userInfo.put("Cúc chùm trung","0 bó");
        userInfo.put("Cúc chùm xả","0 bó");
        userInfo.put("Cúc một lưới đóa cũ","0 bó");
        userInfo.put("Cúc một lưới đóa mới","0 bó");
        userInfo.put("Cúc một lưới xanh","0 bó");
        userInfo.put("Cúc một lưới trắng","0 bó");
        userInfo.put("Cúc một lưới nhuộm màu","0 bó");
        userInfo.put("Cúc một lưới nhuộm màu đỏ","0 bó");
        userInfo.put("Cúc một lưới nhuộm màu cam","0 bó");
        userInfo.put("Cúc một lưới nhuộm màu xanh đậm","0 bó");
        userInfo.put("Cúc một lưới nhuộm màu xanh lá","0 bó");
        userInfo.put("Cúc một lưới nhuộm màu tím","0 bó");
        userInfo.put("Cúc một kim cương","0 bó");
        userInfo.put("Cúc một kim cương trung","0 bó");
        userInfo.put("Cúc một chén Saphia","0 bó");
        userInfo.put("Cúc một ping pong","0 bó");
        userInfo.put("Cúc một chén đóa mới","0 bó");
        userInfo.put("Cúc một lưới trung","0 bó");
        userInfo.put("Cúc một bi vàng","0 bó");
        userInfo.put("Cúc một bi trắng","0 bó");
        userInfo.put("Cát tường (bó)","0 bó");
        userInfo.put("Cát tường (kg)","0 kg");
        userInfo.put("Hướng dương (cành)","0 cành");
        userInfo.put("Hướng dương (bó)","0 bó");
        userInfo.put("Tú cầu","0 cành");
        userInfo.put("Cẩm chướng (cành)","0 cành");
        userInfo.put("Cẩm chướng (bó)","0 bó");
        userInfo.put("Đồng tiền không quấn","0 bó");
        userInfo.put("Đồng tiền quấn","0 bó");
        userInfo.put("Dơn đỏ","0 bó");
        userInfo.put("Dơn vàng","0 bó");
        userInfo.put("Dơn hồng","0 bó");
        userInfo.put("Dơn trung","0 bó");
        userInfo.put("Lan vỉ trắng","0 vỉ");
        userInfo.put("Lan vỉ tím","0 vỉ");
        userInfo.put("Lan vỉ vàng","0 vỉ");
        userInfo.put("Mõm sói","0 bó");
        userInfo.put("Môn các loại (cành)","0 cành");
        userInfo.put("Môn các loại (bó)","0 bó");
        userInfo.put("Hoa hồng đủ màu","0 cành");
        userInfo.put("Hoa hồng sen mới","0 cành");
        userInfo.put("Hoa hồng sen","0 cành");
        userInfo.put("Hoa hồng sen đại","0 cành");
        userInfo.put("Hoa hồng cam dài","0 cành");
        userInfo.put("Hoa hồng ánh trăng","0 cành");
        userInfo.put("Hoa hồng đỏ sa","0 cành");
        userInfo.put("Hoa hồng đỏ Hà Lan","0 cành");
        userInfo.put("Hoa hồng đỏ ớt","0 cành");
        userInfo.put("Hoa hồng phấn","0 cành");
        userInfo.put("Hoa hồng hoàng hậu","0 cành");
        userInfo.put("Hoa hồng mỡ gà","0 cành");
        userInfo.put("Hoa hồng kem","0 cành");
        userInfo.put("Hoa hồng trắng xoáy","0 cành");
        userInfo.put("Hoa hồng xanh ngọc","0 cành");
        userInfo.put("Hoa hồng hỷ","0 cành");
        userInfo.put("Hoa hồng hỷ xanh","0 cành");
        userInfo.put("Hoa hồng hỷ hồng","0 cành");
        userInfo.put("Hoa hồng tím","0 cành");
        userInfo.put("Hoa hồng tím cồ","0 cành");
        userInfo.put("Hoa hồng nhỏ","0 cành");
        userInfo.put("Hoa hồng vàng chùa","0 cành");
        userInfo.put("Hoa hồng sen phật","0 cành");
        userInfo.put("Hoa hồng mật ong","0 cành");
        userInfo.put("Hoa hồng Hara","0 cành");
        userInfo.put("Hoa hồng son môi","0 cành");
        userInfo.put("Hoa hồng trà","0 cành");
        userInfo.put("Ly nhọn 1 tai","0 bó");
        userInfo.put("Ly nhọn 2 tai","0 bó");
        userInfo.put("Ly nhọn 3 tai","0 bó");
        userInfo.put("Ly nhọn 4 tai","0 bó");
        userInfo.put("Ly nhọn 5 tai","0 bó");
        userInfo.put("Ly ù đỏ 1 tai","0 bó");
        userInfo.put("Ly ù đỏ 2 tai","0 bó");
        userInfo.put("Ly ù đỏ 3 tai","0 bó");
        userInfo.put("Ly ù đỏ 4 tai","0 bó");
        userInfo.put("Ly ù đỏ 5 tai","0 bó");
        userInfo.put("Ly ù vàng 1 tai","0 bó");
        userInfo.put("Ly ù vàng 2 tai","0 bó");
        userInfo.put("Ly ù vàng 3 tai","0 bó");
        userInfo.put("Ly ù vàng 4 tai","0 bó");
        userInfo.put("Ly ù vàng 5 tai","0 bó");
        userInfo.put("Dừa nhỏ","0 bó");
        userInfo.put("Dừa lớn","0 bó");
        userInfo.put("Lá lan","0 bó");
        userInfo.put("Lá mimosa","0 bó");
        userInfo.put("Lá nguyệt quế","0 bó");
        userInfo.put("Lá đốm","0 bó");
        userInfo.put("Lá đô la","0 bó");
        userInfo.put("Thạch thảo tím (kg)","0 kg");
        userInfo.put("Thạch thảo tím (bó)","0 bó");
        userInfo.put("Thạch thảo trắng (kg)","0 kg");
        userInfo.put("Thạch thảo trắng (bó)","0 bó");
        userInfo.put("Vàng anh (kg)","0 kg");
        userInfo.put("Vàng anh (bó)","0 bó");
        userInfo.put("Sa lem (kg)","0 kg");
        userInfo.put("Sa lem (bó)","0 bó");
        userInfo.put("Sao tím (kg)","0 kg");
        userInfo.put("Sao tím (bó)","0 bó");
        userInfo.put("Bibi","0 bó");
        userInfo.put("Bibi ngoại","0 bó");
        userInfo.put("Mimi","0 bó");

        return userInfo;
    }
}
